name: Playwright Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  NODE_VERSION: 24.11.0

  SAUCEDEMO_BASE_URL: ${{ vars.SAUCEDEMO_BASE_URL || 'https://www.saucedemo.com' }}
  SAUCEDEMO_USERNAME_STANDARD_USER: ${{ secrets.SAUCEDEMO_USERNAME_STANDARD_USER }}
  SAUCEDEMO_PASSWORD_STANDARD_USER: ${{ secrets.SAUCEDEMO_PASSWORD_STANDARD_USER }}
  SAUCEDEMO_USERNAME_LOCKED_OUT_USER: ${{ secrets.SAUCEDEMO_USERNAME_LOCKED_OUT_USER }}
  SAUCEDEMO_PASSWORD_LOCKED_OUT_USER: ${{ secrets.SAUCEDEMO_PASSWORD_LOCKED_OUT_USER }}
  SAUCEDEMO_USERNAME_PROBLEM_USER: ${{ secrets.SAUCEDEMO_USERNAME_PROBLEM_USER }}
  SAUCEDEMO_PASSWORD_PROBLEM_USER: ${{ secrets.SAUCEDEMO_PASSWORD_PROBLEM_USER }}
  SAUCEDEMO_USERNAME_PERFORMANCE_GLITCH_USER: ${{ secrets.SAUCEDEMO_USERNAME_PERFORMANCE_GLITCH_USER }}
  SAUCEDEMO_PASSWORD_PERFORMANCE_GLITCH_USER: ${{ secrets.SAUCEDEMO_PASSWORD_PERFORMANCE_GLITCH_USER }}
  SAUCEDEMO_USERNAME_ERROR_USER: ${{ secrets.SAUCEDEMO_USERNAME_ERROR_USER }}
  SAUCEDEMO_PASSWORD_ERROR_USER: ${{ secrets.SAUCEDEMO_PASSWORD_ERROR_USER }}
  SAUCEDEMO_USERNAME_VISUAL_USER: ${{ secrets.SAUCEDEMO_USERNAME_VISUAL_USER }}
  SAUCEDEMO_PASSWORD_VISUAL_USER: ${{ secrets.SAUCEDEMO_PASSWORD_VISUAL_USER }}

  ORANGEHRM_BASE_URL: ${{ vars.ORANGEHRM_BASE_URL || 'https://opensource-demo.orangehrmlive.com' }}
  ORANGEHRM_USERNAME: ${{ secrets.ORANGEHRM_USERNAME }}
  ORANGEHRM_PASSWORD: ${{ secrets.ORANGEHRM_PASSWORD }}

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: ./.github/actions/setup-node
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies with cache
        uses: ./.github/actions/npm-ci

      - name: Install Playwright with cache
        uses: ./.github/actions/install-playwright

      - name: Run Playwright tests
        run: npm run test:cov

      - name: Upload coverage report
        uses: ./.github/actions/upload-coverage
        with:
          artifact-name: unit-test-coverage
          codecov-token: ${{ secrets.CODECOV_TOKEN }}
          coverage-file: coverage/cobertura-coverage.xml
          coverage-flags: unit-tests
